//! Vendored surf-icons glyph set (GENERATED table - do not hand-edit entries).
//!
//! Source: CloudSurf's own surf-icons web set (`gen/web/icons/*.svg`, MIT),
//! vendored under `assets/icons/`. An intrinsic `width="16" height="16"` is
//! injected at vendor time so the glyphs carry the same default size as the
//! built-in constants in `icons.rs`; contexts (row badges, toolbar buttons)
//! resize via CSS. Regenerate by re-copying from surf-icons and rebuilding
//! this table; keep it sorted by name (binary-searched).

/// Sorted `(name, svg)` table of every vendored glyph.
pub(crate) static VENDORED_ICONS: &[(&str, &str)] = &[
    ("activity", include_str!("../assets/icons/activity.svg")),
    ("alert-circle", include_str!("../assets/icons/alert-circle.svg")),
    ("apps", include_str!("../assets/icons/apps.svg")),
    ("archive", include_str!("../assets/icons/archive.svg")),
    ("arrow-down", include_str!("../assets/icons/arrow-down.svg")),
    ("arrow-left", include_str!("../assets/icons/arrow-left.svg")),
    ("arrow-right", include_str!("../assets/icons/arrow-right.svg")),
    ("arrow-up", include_str!("../assets/icons/arrow-up.svg")),
    ("award", include_str!("../assets/icons/award.svg")),
    ("bar-chart", include_str!("../assets/icons/bar-chart.svg")),
    ("book", include_str!("../assets/icons/book.svg")),
    ("book-open", include_str!("../assets/icons/book-open.svg")),
    ("bookmark", include_str!("../assets/icons/bookmark.svg")),
    ("box", include_str!("../assets/icons/box.svg")),
    ("briefcase", include_str!("../assets/icons/briefcase.svg")),
    ("calendar", include_str!("../assets/icons/calendar.svg")),
    ("camera", include_str!("../assets/icons/camera.svg")),
    ("check", include_str!("../assets/icons/check.svg")),
    ("check-circle", include_str!("../assets/icons/check-circle.svg")),
    ("chevron-down", include_str!("../assets/icons/chevron-down.svg")),
    ("chevron-left", include_str!("../assets/icons/chevron-left.svg")),
    ("chevron-right", include_str!("../assets/icons/chevron-right.svg")),
    ("chevron-up", include_str!("../assets/icons/chevron-up.svg")),
    ("circle", include_str!("../assets/icons/circle.svg")),
    ("clipboard", include_str!("../assets/icons/clipboard.svg")),
    ("clock", include_str!("../assets/icons/clock.svg")),
    ("cloud", include_str!("../assets/icons/cloud.svg")),
    ("code", include_str!("../assets/icons/code.svg")),
    ("code-repos", include_str!("../assets/icons/code-repos.svg")),
    ("coffee", include_str!("../assets/icons/coffee.svg")),
    ("compass", include_str!("../assets/icons/compass.svg")),
    ("copy", include_str!("../assets/icons/copy.svg")),
    ("create", include_str!("../assets/icons/create.svg")),
    ("credit-card", include_str!("../assets/icons/credit-card.svg")),
    ("database", include_str!("../assets/icons/database.svg")),
    ("deploy", include_str!("../assets/icons/deploy.svg")),
    ("devices", include_str!("../assets/icons/devices.svg")),
    ("docs", include_str!("../assets/icons/docs.svg")),
    ("dollar-sign", include_str!("../assets/icons/dollar-sign.svg")),
    ("domains", include_str!("../assets/icons/domains.svg")),
    ("download", include_str!("../assets/icons/download.svg")),
    ("edit", include_str!("../assets/icons/edit.svg")),
    ("external-link", include_str!("../assets/icons/external-link.svg")),
    ("file", include_str!("../assets/icons/file.svg")),
    ("file-text", include_str!("../assets/icons/file-text.svg")),
    ("files", include_str!("../assets/icons/files.svg")),
    ("filter", include_str!("../assets/icons/filter.svg")),
    ("flag", include_str!("../assets/icons/flag.svg")),
    ("flask", include_str!("../assets/icons/flask.svg")),
    ("folder", include_str!("../assets/icons/folder.svg")),
    ("gift", include_str!("../assets/icons/gift.svg")),
    ("github", include_str!("../assets/icons/github.svg")),
    ("globe", include_str!("../assets/icons/globe.svg")),
    ("heart", include_str!("../assets/icons/heart.svg")),
    ("home", include_str!("../assets/icons/home.svg")),
    ("image", include_str!("../assets/icons/image.svg")),
    ("images", include_str!("../assets/icons/images.svg")),
    ("inbox", include_str!("../assets/icons/inbox.svg")),
    ("info", include_str!("../assets/icons/info.svg")),
    ("layers", include_str!("../assets/icons/layers.svg")),
    ("layout", include_str!("../assets/icons/layout.svg")),
    ("link", include_str!("../assets/icons/link.svg")),
    ("list", include_str!("../assets/icons/list.svg")),
    ("lock", include_str!("../assets/icons/lock.svg")),
    ("mail", include_str!("../assets/icons/mail.svg")),
    ("map", include_str!("../assets/icons/map.svg")),
    ("map-pin", include_str!("../assets/icons/map-pin.svg")),
    ("menu", include_str!("../assets/icons/menu.svg")),
    ("message-circle", include_str!("../assets/icons/message-circle.svg")),
    ("message-square", include_str!("../assets/icons/message-square.svg")),
    ("messages", include_str!("../assets/icons/messages.svg")),
    ("mic", include_str!("../assets/icons/mic.svg")),
    ("minus", include_str!("../assets/icons/minus.svg")),
    ("monitor", include_str!("../assets/icons/monitor.svg")),
    ("moon", include_str!("../assets/icons/moon.svg")),
    ("more", include_str!("../assets/icons/more.svg")),
    ("music", include_str!("../assets/icons/music.svg")),
    ("new-chat", include_str!("../assets/icons/new-chat.svg")),
    ("newspaper", include_str!("../assets/icons/newspaper.svg")),
    ("notebook", include_str!("../assets/icons/notebook.svg")),
    ("notifications", include_str!("../assets/icons/notifications.svg")),
    ("package", include_str!("../assets/icons/package.svg")),
    ("phone", include_str!("../assets/icons/phone.svg")),
    ("pie-chart", include_str!("../assets/icons/pie-chart.svg")),
    ("play", include_str!("../assets/icons/play.svg")),
    ("plus", include_str!("../assets/icons/plus.svg")),
    ("plus-circle", include_str!("../assets/icons/plus-circle.svg")),
    ("refresh-cw", include_str!("../assets/icons/refresh-cw.svg")),
    ("ruler", include_str!("../assets/icons/ruler.svg")),
    ("scissors", include_str!("../assets/icons/scissors.svg")),
    ("search", include_str!("../assets/icons/search.svg")),
    ("send", include_str!("../assets/icons/send.svg")),
    ("settings", include_str!("../assets/icons/settings.svg")),
    ("share", include_str!("../assets/icons/share.svg")),
    ("shield", include_str!("../assets/icons/shield.svg")),
    ("shopping-bag", include_str!("../assets/icons/shopping-bag.svg")),
    ("shopping-cart", include_str!("../assets/icons/shopping-cart.svg")),
    ("smartphone", include_str!("../assets/icons/smartphone.svg")),
    ("star", include_str!("../assets/icons/star.svg")),
    ("sun", include_str!("../assets/icons/sun.svg")),
    ("surf-emblem", include_str!("../assets/icons/surf-emblem.svg")),
    ("surfy", include_str!("../assets/icons/surfy.svg")),
    ("surfy-fin", include_str!("../assets/icons/surfy-fin.svg")),
    ("tag", include_str!("../assets/icons/tag.svg")),
    ("target", include_str!("../assets/icons/target.svg")),
    ("tasks", include_str!("../assets/icons/tasks.svg")),
    ("thumbs-down", include_str!("../assets/icons/thumbs-down.svg")),
    ("thumbs-up", include_str!("../assets/icons/thumbs-up.svg")),
    ("tier-free", include_str!("../assets/icons/tier-free.svg")),
    ("tier-premium", include_str!("../assets/icons/tier-premium.svg")),
    ("tier-pro", include_str!("../assets/icons/tier-pro.svg")),
    ("tier-ultra", include_str!("../assets/icons/tier-ultra.svg")),
    ("trash", include_str!("../assets/icons/trash.svg")),
    ("trending-up", include_str!("../assets/icons/trending-up.svg")),
    ("trophy", include_str!("../assets/icons/trophy.svg")),
    ("truck", include_str!("../assets/icons/truck.svg")),
    ("upload", include_str!("../assets/icons/upload.svg")),
    ("user", include_str!("../assets/icons/user.svg")),
    ("users", include_str!("../assets/icons/users.svg")),
    ("video", include_str!("../assets/icons/video.svg")),
    ("wallet", include_str!("../assets/icons/wallet.svg")),
    ("waves", include_str!("../assets/icons/waves.svg")),
    ("wavesite", include_str!("../assets/icons/wavesite.svg")),
    ("wind", include_str!("../assets/icons/wind.svg")),
    ("workspace", include_str!("../assets/icons/workspace.svg")),
    ("wrench", include_str!("../assets/icons/wrench.svg")),
    ("x", include_str!("../assets/icons/x.svg")),
    ("zap", include_str!("../assets/icons/zap.svg")),
];

/// Look up a vendored glyph by exact name.
pub(crate) fn vendored_icon(name: &str) -> Option<&'static str> {
    VENDORED_ICONS
        .binary_search_by(|(n, _)| n.cmp(&name))
        .ok()
        .map(|i| VENDORED_ICONS[i].1)
}
